openapi: 3.0.3
info:
  title: vehicle-restrictions
  version: "0.5"

paths:
  /{year}/{city_code}.json:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/restrictions"
        "404":
          description: Not found
          content:
            text/plain:
              schema:
                type: string
    parameters:
      - in: path
        required: true
        schema:
          type: string
          pattern: '^20[0-9]{2}$'
        name: year
        example: "2024"
        description: Restriction year
      - in: path
        required: true
        schema:
          type: string
          pattern: '^[a-z]{2}\-[a-z]{2,3}\-[a-z]{3,}$'
        name: city_code
        example: "co-ant-medellin"
        description: Country prefix (ISO 3166-2), followed by region and city name

  /{year}/{country_code}-hollidays.json:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/hollidays"
        "404":
          description: Not found
          content:
            text/plain:
              schema:
                type: string
    parameters:
      - in: path
        required: true
        schema:
          type: string
          pattern: '^20[0-9]{2}$'
        name: year
        example: "2024"
        description: Holliday year
      - in: path
        required: true
        schema:
          type: string
          pattern: '^[a-z]{2}$'
        name: country_code
        example: "co"
        description: Country prefix (ISO 3166-2)      

servers:
  - url: https://raw.githubusercontent.com/iojancode/vehicle-restrictions/master

components:
  schemas:
    tz:
      type: string
      description: Time zone for restrictions from 'tz database'
      example: "America/Bogota"

    datetime:
      type: string
      description: Date and time with time zone
      example: "2022-01-16T12:00:00-05:00"

    time:
      type: string
      description: Time using a 24-hour clock, minutes and seconds
      example: "18:00:00"

    dayofmonth:
      type: integer
      minimum: 1
      maximum: 31   
      description: Day of the month from 1 to 31

    dayofweek:
      type: string
      description: Day of the week in English
      enum:
        - Sunday
        - Monday
        - Tuesday
        - Wednesday
        - Thursday
        - Friday
        - Saturday

    regex:
      type: string
      description: Standard regular expression
      example: "^[A-Z]{3}[0-9]{2}[6-9]$"

    rule:
      type: object
      description: Rule object descriptor
      required:
        - since
        - until
        - hollidays
        - label
        - legend
      properties:
        since:
          description: Date since this rule applies
          $ref: "#/components/schemas/datetime"
          nullable: false
        until:
          description: Date until this rule applies
          $ref: "#/components/schemas/datetime"
          nullable: false
        label:
          description: Restriction label
          type: string
          nullable: false
        legend:
          description: Rule legend
          type: string
          nullable: false
        holliday:
          description: Whether this rule applies only on a holiday or excludes it
          type: boolean
          nullable: true
        daysOfMonth:
          description: Days of the month for which this rule applies
          type: array
          items:
            $ref: "#/components/schemas/dayofmonth"
          nullable: true
        daysOfWeek:
          description: Weekdays for which this rule applies
          type: array
          items:
            $ref: "#/components/schemas/dayofweek"
          nullable: true
        startsAt:
          description: Time of day when this rule starts to apply
          $ref: "#/components/schemas/time"
          nullable: true
        endsAt:
          description: Time of day when this rule ends to apply
          $ref: "#/components/schemas/time"
          nullable: true
        plateRegex:
          description: Licence plates for which this rule applies
          $ref: "#/components/schemas/regex"
          nullable: true
        serviceKind:
          description: Vehicle service kind for which this rule applies
          type: string
          nullable: true
          enum:
            - Particular         
        fuelType:
          description: Vehicle fuel type for which this rule applies
          type: string
          nullable: true
          enum:
            - GASOLINA   

    restrictions:
      type: object
      description: Base response object for restrictions
      required:
        - timeZone
        - updated
        - rules
      properties:
        timeZone:
          description: Time zone for this restrictions
          $ref: "#/components/schemas/tz"
          nullable: false
        updated:
          description: Last update for this restrictions
          $ref: "#/components/schemas/datetime"
          nullable: false
        rules:
          description: The rules
          type: array
          items:
            $ref: "#/components/schemas/rule"
          nullable: false

    event:
      type: object
      description: Event object descriptor
      required:
        - since
        - until
      properties:
        since:
          description: Date since this event applies
          $ref: "#/components/schemas/datetime"
          nullable: false
        until:
          description: Date until this event applies
          $ref: "#/components/schemas/datetime"
          nullable: false
        label:
          description: Event label
          type: string
          nullable: true  

    hollidays:
      type: object
      description: Base response object for holliday
      required:
        - timeZone
        - updated
        - events
      properties:
        timeZone:
          description: Time zone for this hollidays
          $ref: "#/components/schemas/tz"
          nullable: false
        updated:
          description: Last update for this hollidays
          $ref: "#/components/schemas/datetime"
          nullable: false
        events:
          description: The holliday events
          type: array
          items:
            $ref: "#/components/schemas/event"
          nullable: false          